
package com.packt.maven.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BookWS", targetNamespace = "http://ws.maven.packt.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookWS {


    /**
     * 
     * @return
     *     returns java.util.List<com.packt.maven.ws.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllBook", targetNamespace = "http://ws.maven.packt.com/", className = "com.packt.maven.ws.FindAllBook")
    @ResponseWrapper(localName = "findAllBookResponse", targetNamespace = "http://ws.maven.packt.com/", className = "com.packt.maven.ws.FindAllBookResponse")
    public List<Book> findAllBook();

}
