
package com.packt.maven.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BookWSService", targetNamespace = "http://ws.maven.packt.com/", wsdlLocation = "http://localhost:8080/WebServiceModule/book?wsdl")
public class BookWSService
    extends Service
{

    private final static URL BOOKWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.packt.maven.ws.BookWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.packt.maven.ws.BookWSService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/WebServiceModule/book?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/WebServiceModule/book?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BOOKWSSERVICE_WSDL_LOCATION = url;
    }

    public BookWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookWSService() {
        super(BOOKWSSERVICE_WSDL_LOCATION, new QName("http://ws.maven.packt.com/", "BookWSService"));
    }

    /**
     * 
     * @return
     *     returns BookWS
     */
    @WebEndpoint(name = "BookWSPort")
    public BookWS getBookWSPort() {
        return super.getPort(new QName("http://ws.maven.packt.com/", "BookWSPort"), BookWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookWS
     */
    @WebEndpoint(name = "BookWSPort")
    public BookWS getBookWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.maven.packt.com/", "BookWSPort"), BookWS.class, features);
    }

}
